### ISSUE TITLE
Cant change the rate property of the Video component dynamically

### ISSUE THREAD

**Issue by iashwinprasada** [itsnubix/react-native-video-controls#101]

**Comment by kylemilloy** [comment]
Please provide a description, sample code, steps to reproduce....anything really. Closing this until that time.

![Help me, help you](https://media.giphy.com/media/uRb2p09vY8lEs/giphy.gif)

**Comment by fabdrol** [comment]
@kylemilloy I've run into this issue as well; see details below:

**Context**
Video player mounted with `rate` set from component state. Rate can be changed using a picker that pops-up by pressing an on-screen button.

```javascript
<VideoPlayer
  ref={ref => { this.videoPlayer = ref }}
  source={{ ... }}
  rate={this.state.rate}
  volume={0}
  paused={this.state.paused}
  onProgress={data => this.setState({ currentTime: data.currentTime })}
  onBack={() => { this.props.closeVideoPlayer() }}
  onLoad={this.onVideoLoad}
  disablePlayPause
  disableVolume
  disableFullscreen
/>
```

**Expected behaviour**
When changing the state by tapping the button, the video player rate should slow down or speed up.

**Actual behaviour**
The player rate does not change. When it's set at mount time (this.state in the constructor) it does play at the specified rate.

**Comment by mitchdowney** [comment]
@kylemilloy was this issue ever resolved? I am running into the same issue as @fabdrol. Whatever I first have the rate set to when the component renders is what stays the rate of the Video player. When I change the rate with a state update, I verify the state.rate changes, but the video does not change its rate.
