### ISSUE TITLE
Seeker Button too small to use on a device

### ISSUE THREAD

**Issue by yordok** [itsnubix/react-native-video-controls#102]
This is more of a request for an enhancement, but I currently find the seeker button/slider hard to press with my thumb.  Perhaps this could be made customizable with a prop.

Any chance that this could be considered for an enhancement?  If not I'd be happy to open a PR for it.

**Comment by kylemilloy** [comment]
This is a common one...

We found difficulties with testing where if things get too big, hitboxes overlap and (for example) instead of triggering the play/pause you trigger the seek bar. We spent a couple days A/B testing with the team here to find what was optimum. At this time we're not looking to revisit making changes to the UI until a major release but you're free to modify the styles. In `VideoPlayer.js` these styles are set around line 1280.

Let me know if you have any other questions

**Comment by kylemilloy** [comment]
This is a common one...

We found difficulties with testing where if things get too big, hitboxes overlap and (for example) instead of triggering the play/pause you trigger the seek bar. We spent a couple days A/B testing with the team here to find what was optimum. At this time we're not looking to revisit making changes to the UI until a major release but you're free to modify the styles. In `VideoPlayer.js` these styles are set around lines 1200-1300.

Let me know if you have any other questions
