### ISSUE TITLE
onLoad

### ISSUE THREAD

**Issue by YeYinhai** [itsnubix/react-native-video-controls#14]
OnLoad with BUG
Causes the Load icon to appear

**Comment by kylemilloy** [comment]
Can you send me a bit of details? What version of React Native, what version of react-native-video-controls, etc.

**Comment by YeYinhai** [comment]
onLoadStart={ () => {} }     // Fired when loading of the source starts
    onProgress={ () => {} }      // Fired every ~250ms when the video progresses
    onError={ () => {} }         // Fired when an error is encountered on load
    onBack={ () => {} }          // Function fired when back button is pressed.
    onLoad={ () => {} }          // Fired when loading is complete
    onEnd={ () => {} }           // Fired when the video is complete.

        this.events = {
            onLoadStart: this.props.onLoadStart || this._onLoadStart.bind( this ),
            onProgress: this.props.onProgress || this._onProgress.bind( this ),
            onError: this.props.onError || this._onError.bind( this ),
            onLoad: this.props.onLoad || this._onLoad.bind( this ),
            onEnd: this.props.onEnd || this._onEnd.bind( this ),
            onScreenPress: this._onScreenPress.bind( this ),
        };

RN0.39.2 android6.0.1  react-native-video-controls 1.1.1

I saw your code.
All custom events will replace the events you wrote
Appear BUG

**Comment by YeYinhai** [comment]
Yes。
Custom events should not replace the original event。

**Comment by kylemilloy** [comment]
Removed onLoad events from being editable in 1.2.x

**Comment by FuadBalashov** [comment]
@kylemilloy I realize I am late to this party but I think that removing the ability to pass an onLoad is not a good idea. Could I get your thoughts on this?

I just started looking at this library after working with react-native-video and need to use the onLoad to be able to get the the width and height of the video that is loaded so I can resize the component  to fill the screen width and scale the height based on the aspect ratio. That being said I think it makes sense to not remove the original onLoad event since your component relies on the logic in there.

Based on this I would suggest that your onLoad calls the onLoad passed in with the props with the arguments it receives. (you may want to do this with all of the callback props that were removed) Thoughts?

Id be happy to contribute with a PR based on what we decide.

**Comment by kylemilloy** [comment]
Pull away, my son. Thanks for the help.
