### ISSUE TITLE
Seek methods on react native video controls

### ISSUE THREAD

**Issue by Marrryy** [itsnubix/react-native-video-controls#226]
I know this is rare occasion..
I want to build slider that can do like seekbar. 

i want the other functions on react native video controls.
I try console ref on react-native-video-controls, and there no method seek on ref...

Is there any method like seek in react-native-video on react-native-video-controls ?

**Comment by kylemilloy** [comment]
You should be able to use [`seekTo`](https://github.com/itsnubix/react-native-video-controls/blob/master/VideoPlayer.js#L651)

Otherwise, I've buried the `react-native-video` player ref as you _shouldn't_ need to access it but if you want to you can get a reference to the video itself by doing:

```js
<VideoPlayer
  ref={ videoPlayer => this.videoRef = videoPlayer.player.ref  } // <- the reference to the actual <Video> component is on 
```

See more here: #92

**Comment by kylemilloy** [comment]
So in the example above if you get reference to the `VideoPlayer` component you can use seekTo. Otherwise you can directly access the `Video` component by drilling for the reference with `ref={ videoPlayer => this.videoRef = videoPlayer.player.ref }`
